language: generic
sudo: required

services: 
  - docker

before_install:
  - docker build -t stefanmijic/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true stefanmijic/docker-react npm run test -- --coverage